# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goodadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='StartDate2',
        ),
        migrations.AlterField(
            model_name='competition',
            name='CompID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
