# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-26 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodadmin', '0002_auto_20180520_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='StockEndPrice',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='stockpick',
            name='StockProfit',
            field=models.FloatField(default=0.0),
        ),
    ]
