# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodadmin', '0003_auto_20180525_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='StockCode',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
