# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodadmin', '0004_stockpick_stockcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpick',
            name='PickDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
